name: sistema-apoio-desabrigados
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}